version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/jobs.phpaustralia.org
permissions:
  - object: /var/www/jobs.phpaustralia.org
    pattern: "**"
    except: [artisan]
    owner: www-data
    group: www-data
    mode: 664
    type:
      - file
  - object: /var/www/jobs.phpaustralia.org
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 775
    type:
      - directory
  - object: /var/www/jobs.phpaustralia.org
    pattern: "artisan"
    owner: www-data
    group: www-data
    mode: 775
    type:
      - file
hooks:
  BeforeInstall:
    - location: deployment/bin/install_environment.sh
      timeout: 300
      runas: root
    - location: deployment/bin/stop_services.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: deployment/bin/configure.sh
      timeout: 300
      runas: root
    - location: deployment/bin/start_services.sh
      timeout: 60
      runas: root
